source 'https://github.com/CocoaPods/Specs.git'

target 'MOLoaderView', :exclusive => true do
  pod "MOLoaderView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MOLoaderView", :path => "../"

  
end
